project:
  type: website
  output-dir: docs

website:
  title: "CASA / Arup City Modelling Lab"
  navbar:
    background: "#f0eeeb"
    logo: images/CML_logo_CL.png
    logo-alt: "CASA/ARUP city modelling lab logo"
    title: false
    pinned: true
    right:
      - href: about/about.qmd
        text: About
      - href: people/index.qmd
        text: People
      - href: projects/index.qmd
        text: Projects
      - href: blog/index.qmd
        text: Blog
      - href: presentations/index.qmd
        text: Presentations  
      - icon: bluesky
        url: https://bsky.app/profile/casaucl.bsky.social
      - icon: twitter-x
        url: https://x.com/CASAUCL
      - icon: github
        url: https://github.com/CityModellingLab
          # - text: Report a Bug
          #   url:  https://github.com/CityModellingLab/cml_casa_website/issues
  repo-url: https://github.com/CityModellingLab/cml_casa_website
  repo-actions: [source]
  page-footer: 
    background: "#f0eeeb"
    left: |
      Copyright 2024, [UCL CASA](https://www.ucl.ac.uk/bartlett/casa/)
    right: |
      [![](/images/University_College_London_logo.svg){fig-alt="UCL" width=150px}](https://www.ucl.ac.uk/)

format:
  html:
    theme: lux
    css: styles.css
    toc: true
    grid:
      sidebar-width: 0px
      body-width: 1000px
      margin-width: 250px
    include-in-header:
      - text: |
          <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.12.1/font/bootstrap-icons.css">

editor: visual

resources:
  - CNAME